name: Check Last Updated Fields

on:
  pull_request:
    paths:
      - 'content/resources/faq/**'
      - 'content/resources/articles/**'
  push:
    branches:
      - '**'
    paths:
      - 'content/resources/faq/**'
      - 'content/resources/articles/**'

jobs:
  check-last-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Last Updated Check
        run: node scripts/check-last-updated.js
